### ISSUE TITLE
Bug: RestAPI calls

### ISSUE THREAD

**Issue by b-bayrak** [ntnu-ai-lab/mycbr-rest#52]
Calls that are not working:
- [/analytics/concepts/{conceptID}/amalgamationFunctions/{amalgamationFunctionID}/detailedCaseComparison]
- [/analytics/concepts/{conceptID}/amalgamationFunctions/{amalgamationFunctionID}/localSimComparison]
- [/concepts/{conceptID}/casebases/{casebaseID}/cases]
- [/concepts/{conceptID}/casebases/{casebaseID}/cases/{caseID}]

**Comment by kerstinbach** [comment]
[/analytics/concepts/{conceptID}/amalgamationFunctions/{amalgamationFunctionID}/detailedCaseComparison] works
[/analytics/concepts/{conceptID}/amalgamationFunctions/{amalgamationFunctionID}/localSimComparison] works

**Comment by kerstinbach** [comment]
Remaining delete calls are fixed with https://github.com/ntnu-ai-lab/mycbr-rest/pull/53
